emotions = {
    b'\xf0\x9f\x98\x84': 'happy',
    b'\xF0\x9F\x98\x81': 'happy',
    b'\xF0\x9F\x98\x82': 'happy',
    b'\xF0\x9F\x98\x80': 'happy',
    b'\xF0\x9F\x98\x8A': 'happy',
    b'\xF0\x9F\x98\x86': 'happy',
    b'\xf0\x9f\x98\x83': 'happy',
    b'\xf0\x9f\xa4\xa9': 'happy',
    b'\xf0\x9f\xa5\xb3': 'happy',
    b'\xF0\x9F\x98\x92': 'sad',
    b'\xF0\x9F\x98\x9E': 'sad',
    b'\xF0\x9F\x98\x94': 'sad',
    b'\xF0\x9F\x98\x9F': 'sad',
    b'\xF0\x9F\x98\x95': 'sad',
    b'\xe2\x98\xb9': 'sad',
    b'\xF0\x9F\x98\xAB': 'sad',
    b'\xF0\x9F\x98\xA9': 'sad',
    b'\xF0\x9F\x98\x93': 'sad',
    b'\xF0\x9F\x91\xBF': 'angry',
    b'\xF0\x9F\x98\xAC': 'angry',
    b'\xF0\x9F\x98\xA4': 'angry',
    b'\xF0\x9F\x98\xA1': 'angry',
    b'\xF0\x9F\x91\xBA': 'angry',
    b'\xF0\x9F\x92\x80': 'angry',
    b'\xF0\x9F\x98\xA0': 'angry',
    b'\xf0\x9f\xa4\xaf': 'angry',
    b'\xf0\x9f\xa4\xa8': 'angry'
}

response = {
    'happy greeting': 'Hi, i see you are really happy!',
    'sad greeting': 'Hi, don\'t be sad!',
    'angry greeting': 'Hi, omg, someone is angry!',
    'not understood': 'I cannot understand you!',
    'happy happy': 'I am glad you are getting even happier!',
    'sad happy': 'I am glad you feel better!',
    'angry happy': 'It seems like you manadged to calm down!',
    'happy sad': 'Why are you sad? You were so happy.',
    'sad sad': 'I am sorry you are still sad',
    'angry sad': 'Wow, you were angry, now you are sad!',
    'angry angry': 'I feel that you are still angry.',
    'sad angry': 'You were sad and now you are angry!',
    'happy angry': 'What a rollercoaster - you were happy, now you are angry.'
}