// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package matrix

type Matrix struct {
	Rows   int
	Cols   int
	matrix []int
}

func New(n, m int) *Matrix {
	return &Matrix{
		Rows:   n,
		Cols:   m,
		matrix: make([]int, n*m),
	}
}

func (M *Matrix) Get(i, j int) int {
	if i < 0 || i >= M.Rows || j < 0 || j >= M.Cols {
		panic("index error")
	}
	idx := M.Cols*i + j
	return M.matrix[idx]
}

func (M *Matrix) Set(i, j int, v int) {
	if i < 0 || i >= M.Rows || j < 0 || j >= M.Cols {
		panic("index error")
	}
	idx := M.Cols*i + j
	M.matrix[idx] = v
}
